apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: gcp-project-operator
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - gcp-project-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - gcp.managed.openshift.io
  resources:
  - projectclaims
  - projectclaims/status
  - projectclaims/finalizers
  - projectreferences
  - projectreferences/status
  - projectreferences/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
