apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  value: staging
- name: IMAGE_DIGEST
  requred: true
- name: PARENT_FOLDER_ID
  required: true
- name: BILLING_ACCOUNT
  required: true
- name: CCS_CONSOLE_ACCESS
  required: true
- name: DISABLED_REGIONS
  required: true

objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: gcp-project-operator-catalog
  spec:
    sourceType: grpc
    grpcPodConfig:
      securityContextConfig: restricted
    image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
    displayName: gcp-project-operator Registry
    publisher: SRE 

- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: gcp-project-operator-og
  spec:
    targetNamespaces:
    - gcp-project-operator
    upgradeStrategy: TechPreviewUnsafeFailForward 

- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: gcp-project-operator
  spec:
    channel: ${CHANNEL}
    name: gcp-project-operator
    source: gcp-project-operator-catalog
    sourceNamespace: gcp-project-operator

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: gcp-project-operator
  data:
    config.yaml: |
      billingAccount: "${BILLING_ACCOUNT}"
      parentFolderID: "${PARENT_FOLDER_ID}"
      ccsConsoleAccess: ${CCS_CONSOLE_ACCESS}
      disabledRegions: ${DISABLED_REGIONS}
