apiVersion: v1
kind: Template
parameters:
  - name: CHANNEL
    required: false
  - name: PKO_IMAGE
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE_DIGEST
    required: true
  - name: OPERATOR_IMAGE
    required: true
  - name: NAMESPACE
    value: openshift-gcp-project-operator
  - name: REPO_NAME
    value: gcp-project-operator
    required: true
  - name: PARENT_FOLDER_ID
    required: true
  - name: BILLING_ACCOUNT
    required: true
  - name: CCS_CONSOLE_ACCESS
    required: true
  - name: DISABLED_REGIONS
    required: true
metadata:
  name: clusterpackage-template
objects:
  - apiVersion: package-operator.run/v1alpha1
    kind: ClusterPackage
    metadata:
      name: "${REPO_NAME}"
      annotations:
        package-operator.run/collision-protection: IfNoController
    spec:
      image: ${PKO_IMAGE}:${IMAGE_TAG}
      config:
        image: ${OPERATOR_IMAGE}:${IMAGE_TAG}
        billingAccount: ${BILLING_ACCOUNT}
        parentFolderID: ${PARENT_FOLDER_ID}
        ccsConsoleAccess: ${CCS_CONSOLE_ACCESS}
        disabledRegions: ${DISABLED_REGIONS}
