apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projectclaims.gcp.managed.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    description: Status of the project claim
    name: State
    type: string
  - JSONPath: .spec.gcpProjectID
    description: ID of the GCP Project that has been created
    name: GCPProjectID
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: Age since the project claim was created
    name: Age
    type: date
  group: gcp.managed.openshift.io
  names:
    kind: ProjectClaim
    listKind: ProjectClaimList
    plural: projectclaims
    singular: projectclaim
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            availabilityZones:
              items:
                type: string
              type: array
            gcpCredentialSecret:
              properties:
                name:
                  type: string
                namespace:
                  type: string
              required:
              - name
              - namespace
              type: object
            gcpProjectID:
              type: string
            legalEntity:
              properties:
                id:
                  type: string
                name:
                  type: string
              required:
              - name
              - id
              type: object
            projectReferenceCRLink:
              properties:
                name:
                  type: string
                namespace:
                  type: string
              required:
              - name
              - namespace
              type: object
            region:
              type: string
          required:
          - legalEntity
          - gcpCredentialSecret
          - region
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastProbeTime:
                    description: LastProbeTime is the last time we probed the condition.
                    format: date-time
                    type: string
                  lastTransitionTime:
                    description: LastTransitionTime is the last time the condition
                      transitioned from one status to another.
                    format: date-time
                    type: string
                  message:
                    description: Message is a human-readable message indicating details
                      about last transition.
                    type: string
                  reason:
                    description: Reason is a unique, one-word, CamelCase reason for
                      the condition's last transition.
                    type: string
                  status:
                    description: Status is the status of the condition.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            state:
              type: string
          required:
          - conditions
          - state
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
