apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-project-operator
  namespace: gcp-project-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gcp-project-operator
  template:
    metadata:
      labels:
        name: gcp-project-operator
    spec:
      serviceAccountName: gcp-project-operator
      containers:
        - name: gcp-project-operator
          image: quay.io/app-sre/gcp-project-operator
          command:
          - gcp-project-operator
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "10m"
              memory: "100Mi"
            limits:
              cpu: "50m"
              memroy: "200Mi"
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gcp-project-operator"
